---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - environment.yml
  tasks:
    - name: deploy corp-web-01
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: corp-web-01
        networks:
          'vxw-dvs-301-virtualwire-7-sid-5006-Web_Tier_Logical_Switch': 'Overlay-Web-160'
        power_on: yes
        ovf: ~/3-tier-ovas/web-01a_corp.local.ovf
        validate_certs: no
      delegate_to: localhost
    - name: deploy corp-web-02
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: corp-web-02
        networks:
          'vxw-dvs-301-virtualwire-7-sid-5006-Web_Tier_Logical_Switch': 'Overlay-Web-160'
        power_on: yes
        ovf: ~/3-tier-ovas/web-02a_corp.local.ovf
        validate_certs: no
      delegate_to: localhost
    - name: deploy corp-web-03
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: corp-web-03
        networks:
          'vxw-dvs-301-virtualwire-7-sid-5006-Web_Tier_Logical_Switch': 'Overlay-Web-160'
        power_on: yes
        ovf: ~/3-tier-ovas/web-03a_corp.local.ovf
        validate_certs: no
      delegate_to: localhost
    - name: deploy corp-web-04
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: corp-web-04
        networks:
          'vxw-dvs-301-virtualwire-7-sid-5006-Web_Tier_Logical_Switch': 'Overlay-Web-160'
        power_on: yes
        ovf: ~/3-tier-ovas/web-04a_corp.local.ovf
        validate_certs: no
      delegate_to: localhost
    - name: deploy corp-app-01
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: corp-app-01
        networks:
          'vxw-dvs-301-virtualwire-1-sid-5000-App_Tier_Logical_Switch': 'Overlay-App-144'
        power_on: yes
        ovf: ~/3-tier-ovas/app-01a_corp.local.ovf
        validate_certs: no
      delegate_to: localhost
    - name: deploy corp-db-01
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: corp-db-01
        networks:
          'vxw-dvs-301-virtualwire-5-sid-5004-DB_Tier_Logical_Switch': 'Overlay-DB-128'
        power_on: yes
        ovf: ~/3-tier-ovas/db-01a_corp.local.ovf
        validate_certs: no
      delegate_to: localhost