---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - environment.yml
  tasks:
    - name: tag hr-web-01
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        virtual_machine_display_name: hr-web-01
        remove_other_tags: False
        add_tags:
          - scope: "App-Name"
            tag: "HR-App"
          - scope: "App-Tier"
            tag: "Web"
          - scope: "Environment"
            tag: "Prod"
          - scope: "OS-Type"
            tag: "Linux"
    - name: tag hr-app-01
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        virtual_machine_display_name: hr-app-01
        remove_other_tags: False
        add_tags:
          - scope: "App-Name"
            tag: "HR-App"
          - scope: "App-Tier"
            tag: "App"
          - scope: "Environment"
            tag: "Prod"
          - scope: "OS-Type"
            tag: "Linux"
    - name: tag hr-db-01
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        virtual_machine_display_name: hr-db-01
        remove_other_tags: False
        add_tags:
          - scope: "App-Name"
            tag: "HRS-App"
          - scope: "App-Tier"
            tag: "DB"
          - scope: "Environment"
            tag: "Prod"
          - scope: "OS-Type"
            tag: "Linux"