---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - environment.yml
  tasks:
    - name: create Tier1
      vmware.ansible_for_nsxt.nsxt_policy_security_policy:
        hostname: "{{hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        display_name: "Infra-Access"
        state: "present"
        domain_id: "default"
        locked: True
        category: "Infrastructure"
        rules:
          - action "ALLOW"
            description: "Web Tier Access"
            sequence_number: 10
            id: "Web_Tier_Access"
            display_name: "Web Tier Access"
            source_groups: ["ANY"]
            destination_groups: ["/infra/domains/default/groups/Web-Tier-VMs"]
            services: ["/infra/services/HTTPS"]
            notes: "Allow HTTPS Only to Web Tier"
            ip_protocol: IPV4
            scope: 
              - "/infra/domains/default/groups/Web-Tier-VMs"
