---
- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: False
  vars_files:
    - environment.yml
  tasks:
    - name: deploy fin-web-01
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: fin-web-01
        networks:
          'Overlay-Web-160': 'Overlay-Web-160'
        power_on: yes
        ovf: '{{ ova_path }}fin-app-ovfs/fin-web-01/fin-web-01.ovf'
        validate_certs: no
      delegate_to: localhost
    - name: deploy fin-web-02
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: fin-web-02
        networks:
          'Overlay-Web-160': 'Overlay-Web-160'
        power_on: yes
        ovf: '{{ ova_path }}fin-app-ovfs/fin-web-02/fin-web-02.ovf'
        validate_certs: no
      delegate_to: localhost
    - name: deploy fin-app-01
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: fin-app-01
        networks:
          'Overlay-App-144': 'Overlay-App-144'
        power_on: yes
        ovf: '{{ ova_path }}fin-app-ovfs/fin-app-01/fin-app-01.ovf'
        validate_certs: no
      delegate_to: localhost
    - name: deploy corp-db-01
      community.vmware.vmware_deploy_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        datacenter: '{{ vc_datacenter }}'
        cluster: '{{vc_cluster }}'
        datastore: '{{vc_datastore }}'
        name: fin-db-01
        networks:
          'Overlay-DB-128': 'Overlay-DB-128'
        power_on: yes
        ovf: '{{ ova_path }}fin-app-ovfs/fin-db-01/fin-db-01.ovf'
        validate_certs: no
      delegate_to: localhost
    - name: tag fin-web-01
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        virtual_machine_display_name: fin-web-01
        remove_other_tags: False
        add_tags:
          - scope: "App-Name"
            tag: "Fin-App"
          - scope: "App-Tier"
            tag: "Web"
          - scope: "Environment"
            tag: "Demo"
          - scope: "OS-Type"
            tag: "Linux"
    - name: tag fin-web-02
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        virtual_machine_display_name: fin-web-02
        remove_other_tags: False
        add_tags:
          - scope: "App-Name"
            tag: "Fin-App"
          - scope: "App-Tier"
            tag: "Web"
          - scope: "Environment"
            tag: "Demo"
          - scope: "OS-Type"
            tag: "Linux"
    - name: tag fin-app-01
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        virtual_machine_display_name: fin-app-01
        remove_other_tags: False
        add_tags:
          - scope: "App-Name"
            tag: "Fin-App"
          - scope: "App-Tier"
            tag: "App"
          - scope: "Environment"
            tag: "Demo"
          - scope: "OS-Type"
            tag: "Linux"
    - name: tag fin-db-01
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        virtual_machine_display_name: fin-db-01
        remove_other_tags: False
        add_tags:
          - scope: "App-Name"
            tag: "Fin-App"
          - scope: "App-Tier"
            tag: "DB"
          - scope: "Environment"
            tag: "Demo"
          - scope: "OS-Type"
            tag: "Linux"
    - name: create Fin App Group
      vmware.ansible_for_nsxt.nsxt_policy_group:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        display_name: Fin-App-VMs
        state: "present"
        domain_id: "default"
        expression:
          - member_type: "VirtualMachine"
            value: "App-Name|Fin-App"
            key: "Tag"
            operator: "EQUALS"
            resource_type: "Condition"
    - name: create Fin App Isolation Policy
      vmware.ansible_for_nsxt.nsxt_policy_security_policy:
        hostname: "{{nsxt_hostname}}"
        nsx_cert_path: "{{nsx_cert_path}}"
        validate_certs: False
        display_name: "Infra-Rules"
        state: "present"
        domain_id: "default"
        locked: True
        category: "Environment"
        rules:
        - action: "DROP"
          description: "Isolate the Fin App"
          sequence_number: 100
          display_name: "Fin-App-Isolation"
          destinations_excluded: true
          direction: "IN_OUT"
          source_groups: ["/infra/domains/default/groups/Fin-App-VMs"]
          destination_groups: ["/infra/domains/default/groups/Fin-App-VMs"]
          services: ["/infra/services/SSH"]
          notes: "Isolate the financial application so it does not talk to other apps"
          ip_protocol: IPV4
          scope: 
            - "/infra/domains/default/groups/Fin-App-VMs"