---
- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: False
  vars_files:
    - environment.yml
  tasks:
    - name: Power down fin-web-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-web-01"
        state: shutdown-guest
      delegate_to: localhost
    - name: Pause for 25 Seconds
      ansible.builtin.pause:
        seconds: 25
    - name: dowload fin-web-01
      community.vmware.vmware_export_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-web-01"
        export_dir: '{{ ova_path }}fin-app-ovfs/'
      delegate_to: localhost
    - name: Power up fin-web-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-web-01"
        state: powered-on
      delegate_to: localhost
    - name: Power down fin-web-02
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-web-02"
        state: shutdown-guest
    - name: Pause for 25 Seconds
      ansible.builtin.pause:
        seconds: 25
    - name: dowload fin-web-02
      community.vmware.vmware_export_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-web-02"
        export_dir: '{{ ova_path }}fin-app-ovfs/'
      delegate_to: localhost
    - name: Power up fin-web-02
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-web-02"
        state: powered-on
      delegate_to: localhost
    - name: Power down fin-app-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-app-01"
        state: shutdown-guest
      delegate_to: localhost
    - name: Pause for 25 Seconds
      ansible.builtin.pause:
        seconds: 25
    - name: dowload fin-app-01
      community.vmware.vmware_export_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-app-01"
        export_dir: '{{ ova_path }}fin-app-ovfs/'
      delegate_to: localhost
    - name: Power up fin-app-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-app-01"
        state: powered-on
      delegate_to: localhost
    - name: Power down fin-db-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-db-01"
        state: shutdown-guest
      delegate_to: localhost
    - name: Pause for 25 Seconds
      ansible.builtin.pause:
        seconds: 25
    - name: dowload fin-db-01
      community.vmware.vmware_export_ovf:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-db-01"
        export_dir: '{{ ova_path }}fin-app-ovfs/'
      delegate_to: localhost
    - name: Power up fin-db-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-db-01"
        state: powered-on
      delegate_to: localhost