---
- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: False
  vars_files:
    - environment.yml
  tasks:
    - name: Power down fin-web-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-web-01"
        state: shutdown-guest
      delegate_to: localhost
    - name: Pause for 12 Seconds
      ansible.builtin.pause:
        seconds: 12
    - name: delete fin-web-01
      community.vmware.vmware_guest:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        name: fin-web-01
        state: absent
        validate_certs: no
      delegate_to: localhost
    - name: Power down fin-web-02
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-web-02"
        state: shutdown-guest
      delegate_to: localhost
    - name: Pause for 12 Seconds
      ansible.builtin.pause:
        seconds: 12
    - name: delete fin-web-02
      community.vmware.vmware_guest:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        name: fin-web-02
        state: absent
        validate_certs: no
      delegate_to: localhost
    - name: Power down fin-app-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-app-01"
        state: shutdown-guest
      delegate_to: localhost
    - name: Pause for 12 Seconds
      ansible.builtin.pause:
        seconds: 12
    - name: delete fin-app-01
      community.vmware.vmware_guest:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        name: fin-app-01
        state: absent
        validate_certs: no
      delegate_to: localhost
    - name: Power down fin-db-01
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        validate_certs: no
        name: "fin-db-01"
        state: shutdown-guest
      delegate_to: localhost
    - name: Pause for 12 Seconds
      ansible.builtin.pause:
        seconds: 12
    - name: delete fin-db-01
      community.vmware.vmware_guest:
        hostname: '{{ vc_hostname }}'
        username: '{{ vc_username }}'
        password: '{{ vc_password }}'
        name: fin-db-01
        state: absent
        validate_certs: no
      delegate_to: localhost